name: Code Analysis

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    code_analysis:
        name: ${{ matrix.actions.name }} on PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.4']

                actions:
                    -   name: Coding Standard
                        run: 'composer test:lint'

                    -   name: PHPStan
                        run: 'composer test:types'

                    -   name: Rector
                        run: 'composer rector'

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php }}

            - name: Install Composer dependencies
              run: composer install --no-progress --no-suggest --prefer-dist --ignore-platform-reqs --optimize-autoloader

            - run: ${{ matrix.actions.run }}
