name: Run tests

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    php-tests:
        name: Testing on PHP${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.4', '8.0']
            fail-fast: false
        env:
            key: cache-v1
            extensions:

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.extensions }}

            - name: Setup problem matchers
              run: |
                echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}

                  key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ matrix.php }}-composer-

            - name: Install Composer dependencies
              run: composer install --no-progress --no-suggest --prefer-dist --ignore-platform-reqs --optimize-autoloader

            - name: Test with phpunit
              run: vendor/bin/phpunit
